spring:
  datasource:
    url: jdbc:mysql://maindatabase.csx7jwouvyzn.ap-northeast-1.rds.amazonaws.com:3306/sodsmain?characterEncoding=utf-8&serverTimezone=UTC
    username: sodsadmin
    password: pxqlu65tcLrm3PqMeWdR
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
    jedis.pool.max-active: 8
    jedis.pool.max-idle: 8
    jedis.pool.max-wait: -1ms
    jedis.pool.min-idle: 0


mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml

server:
  port: 8888